title: Kerem Oktar
logo: /assets/images/edited_a_2_22jpg.jpg
show_downloads: false
description: Ph.D Candidate at Princeton University.<br><a href="https://keremoktar.github.io/assets/Academic_CV-3.pdf">ğŸ“ƒ Click here to see my CV.</a><br><br><a href="https://scholar.google.com/citations?user=wBVlDlYAAAAJ&hl=en&authuser=2">ğŸ“ Google Scholar</a><br><a href="https://twitter.com/keremoktar">ğŸ¦ Twitter</a><br><a href="https://bsky.app/profile/keremoktar.bsky.social">â˜ï¸ Bluesky</a>
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
