title: Kerem Oktar
logo: /assets/images/edited_a_2_22jpg.jpg
show_downloads: false
description: PhD Candidate @ Princeton University<br><b><a href="https://keremoktar.github.io/assets/Academic_CV-3.pdf"><font color="peru">ğŸ“ƒ Click here to see my CV</font></a></b><br><br><a href="https://keremoktar.github.io">ğŸ  Return to homepage</a><br><a href="https://twitter.com/keremoktar">ğŸ¦ Twitter</a>; <a href="https://bsky.app/profile/keremoktar.bsky.social">â˜ï¸ Bluesky</a>; <a href="https://scholar.google.com/citations?user=wBVlDlYAAAAJ&hl=en">ğŸ“ Scholar</a><br><details><summary>ğŸ“ Page Directory</summary><a href="https://keremoktar.com/collaborators.html">Collaborators</a><a href="https://keremoktar.com/advice.html">Grad Application Advice</a><a href="https://keremoktar.com/paperpile.html">List of Favorite Papers</a></details>
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
google_analytics: G-VN01SP2WVS
